### PR TITLE
BDRSPS-589: renamed fields visitOrganisations and surveyOrganisation to visitOrgs and surveyOrgs respectively.

### PR DESCRIPTION
**Pull request by joecrowleygaia**
Another thing to consider is that the fields are pluralised as they are list types. PartA backend will need to be updated following this merge.

### CODE REVIEW

**Comment by serge-gaia** [comment]
Could you also update the CHANGELO.md
https://github.com/gaiaresources/abis-mapping/blob/main/CHANGELOG.md

**Comment by joecrowleygaia** [comment]
> Could you also update the CHANGELO.md https://github.com/gaiaresources/abis-mapping/blob/main/CHANGELOG.md

I've updated it, but wasn't sure if it should be included as it is for SSD templates.

**Comment by serge-gaia** [comment]
My bad, these changes didn't apply to the incidental occurrences. There were no needs to update the changelog which was just for incidental occurrences so far but what you did is still good.

**Comment by joecrowleygaia** [comment]
> My bad, these changes didn't apply to the incidental occurrences. There were no needs to update the changelog which was just for incidental occurrences so far but what you did is still good.

Reverted the changelog commit. Should be good to go.

**Comment by serge-gaia** [comment]
Sorry about that @joecrowleygaia

**Review by serge-gaia — APPROVED** [review]

**Pull request merged**
