### PR TITLE
BDRSPS-947: set package version to 5.0.0-rc1 in prevision of new Tag & Release

### PR DESCRIPTION
**Pull request by serge-gaia**

### CODE REVIEW

**Comment by Lincoln-GR** [comment]
@serge-gaia Can we merge this after #303 so that the tagged doc version has those updates

**Review by Lincoln-GR — APPROVED** [review]

**Comment by Lincoln-GR** [comment]
@serge-gaia good to go

**Comment by serge-gaia** [comment]
> @serge-gaia good to go

@Lincoln-GR , there's #305 but this can go. I'll wait for #305 before tagging.

**Comment by Lincoln-GR** [comment]
@serge-gaia #305 is merged

**Comment by Lincoln-GR** [comment]
@serge-gaia Ready to tag

**Pull request merged**
