### PR TITLE
BDRSPS-1010 Rejigged the extra fields schema creation logic

### PR DESCRIPTION
**Pull request by joecrowleygaia**
Added test to confirm change of behaviour on fields entered midway in the provided csv data, no longer producing a `SchemaError`. It fixes the bug and restores behaviour closer to frictionless base checks...

### CODE REVIEW

**Review by Lincoln-GR — APPROVED** [review]
Looks good, will wait for ok to merge

**Comment by joecrowleygaia** [comment]
i stuffed up majorly here and did work on this branch thinking it was another one. Might need to delete the branch and resubmit.

**Comment by Lincoln-GR** [comment]
@joecrowleygaia reset this branch back to b0ad5daa8dcb5d2afc68c50c4f2cfeda2b857b24 and force push :smiley:

**Comment by Lincoln-GR** [comment]
then cherry-pick 2f5fbf87b3c5c5572d4d57ccc6c8aaa61f04097d and df0fa07385b6e603604d6449ad1b5439adbbb6ec onto a new branch

**Comment by joecrowleygaia** [comment]
I rebased to main and forced push previously thinking i was on the other branch. Cool with that or want me to recreate?

**Comment by Lincoln-GR** [comment]
A rebase is fine

**Comment by Lincoln-GR** [comment]
Looks good :+1:

**Pull request merged**
